# Generated by Django 4.2.4 on 2023-08-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryType', models.CharField(choices=[('earlyBird', 'earlyBird'), ('lateBird', 'lateBird')], max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventCategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPrize', models.IntegerField()),
                ('secondPrize', models.IntegerField()),
                ('thirdPrize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('description', models.TextField(default='Enter description', max_length=1000)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('eventDate', models.DateTimeField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('entryFee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.entryfee')),
                ('eventCategory', models.ForeignKey(default='Choose Category Type', on_delete=django.db.models.deletion.CASCADE, to='event.eventcategory')),
                ('eventType', models.ForeignKey(default='Choose Event Type', on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
                ('prize', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.eventprize')),
                ('venue', models.ForeignKey(default='Choose Venue', on_delete=django.db.models.deletion.CASCADE, to='event.address')),
            ],
        ),
    ]
